version: '3'


services:
  bind9:
      container_name: pvt-dns
      image: ubuntu/bind9:9.18-22.10_edge
      environment:
          - BIND9_USER=root
          - TZ=Europe/Berlin
      ports:
          - "53:53/tcp"
          - "53:53/udp"
      volumes:
          - /etc/bind:/conf
          - /var/cache/bind:/cache
          - /var/lib/bind:/records
      restart: unless-stopped

